import 'package:finance_assistant/finance_assistant.dart';

/// Fixtures generated by `dart run tool/generate_fixtures.dart`, so that every
/// "valid" value here really is checksum-valid rather than merely plausible.
/// Hardcoding a plausible-looking Aadhaar number would produce a red test and
/// tempt someone to "fix" a correct detector.
const String validAadhaar = '234567890124';
const String validCard = '4111111111111111';
const String validIbanGb = 'GB82WEST12345698765432';
const String validIbanDe = 'DE89370400440532013000';
const String validPan = 'ABCPD1234E';
const String validIfsc = 'HDFC0001234';
const String validGstin = '27ABCPD1234E1Z5';
const String validGoogleKey = 'AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY';
const String validHuggingFaceToken = 'hf_abcdefghijklmnopqrstuvwxyz1234';

/// Runs [detector] over [input] and reports whether any span was found.
bool fires(PiiDetector detector, String input) =>
    detector.detect(input).isNotEmpty;

/// Collects the kinds a full default detector sweep reports for [input].
Set<PiiKind> kindsIn(String input) =>
    Redactor().redact(input).spans.map((span) => span.kind).toSet();
